//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "documents"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub document_id: Uuid,
    pub user_id: Uuid,
    pub issuer_id: Uuid,
    pub document_type_id: Uuid,
    pub blockchain_doc_id: Option<String>,
    pub token_id: Option<i64>,
    pub tx_hash: Option<String>,
    pub contract_address: String,
    pub ipfs_hash: Option<String>,
    pub pdf_ipfs_hash: Option<String>,
    pub document_hash: Option<String>,
    pub metadata: Option<Json>,
    pub pdf_schema: Option<Json>,
    pub status: String,
    pub is_valid: bool,
    pub issued_at: Option<DateTime>,
    pub expired_at: Option<DateTime>,
    pub verified_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    DocumentId,
    UserId,
    IssuerId,
    DocumentTypeId,
    BlockchainDocId,
    TokenId,
    TxHash,
    ContractAddress,
    IpfsHash,
    PdfIpfsHash,
    DocumentHash,
    Metadata,
    PdfSchema,
    Status,
    IsValid,
    IssuedAt,
    ExpiredAt,
    VerifiedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    DocumentId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    DocumentType,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::DocumentId => ColumnType::Uuid.def(),
            Self::UserId => ColumnType::Uuid.def(),
            Self::IssuerId => ColumnType::Uuid.def(),
            Self::DocumentTypeId => ColumnType::Uuid.def(),
            Self::BlockchainDocId => ColumnType::String(StringLen::N(66u32)).def().null(),
            Self::TokenId => ColumnType::BigInteger.def().null(),
            Self::TxHash => ColumnType::String(StringLen::N(66u32)).def().null(),
            Self::ContractAddress => ColumnType::String(StringLen::N(42u32)).def(),
            Self::IpfsHash => ColumnType::String(StringLen::None).def().null(),
            Self::PdfIpfsHash => ColumnType::String(StringLen::None).def().null(),
            Self::DocumentHash => ColumnType::String(StringLen::N(66u32)).def().null(),
            Self::Metadata => ColumnType::JsonBinary.def().null(),
            Self::PdfSchema => ColumnType::JsonBinary.def().null(),
            Self::Status => ColumnType::String(StringLen::None).def(),
            Self::IsValid => ColumnType::Boolean.def(),
            Self::IssuedAt => ColumnType::DateTime.def().null(),
            Self::ExpiredAt => ColumnType::DateTime.def().null(),
            Self::VerifiedAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::DocumentType => Entity::belongs_to(super::document_type::Entity)
                .from(Column::DocumentTypeId)
                .to(super::document_type::Column::DocumentTypeId)
                .into(),
        }
    }
}

impl Related<super::document_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
