//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::department::Entity as Department;
pub use super::document_type::Entity as DocumentType;
pub use super::documents::Entity as Documents;
pub use super::major::Entity as Major;
pub use super::otp_verify::Entity as OtpVerify;
pub use super::user::Entity as User;
pub use super::user_major::Entity as UserMajor;
pub use super::user_mfa::Entity as UserMfa;
pub use super::votes::Entity as Votes;
pub use super::voting_events::Entity as VotingEvents;
pub use super::wallet::Entity as Wallet;
