//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "major"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub major_id: Uuid,
    pub name: String,
    pub founding_date: DateTime,
    pub create_at: DateTime,
    pub update_at: DateTime,
    pub department_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    MajorId,
    Name,
    FoundingDate,
    CreateAt,
    UpdateAt,
    DepartmentId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    MajorId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Department,
    UserMajor,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::MajorId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::FoundingDate => ColumnType::DateTime.def(),
            Self::CreateAt => ColumnType::DateTime.def(),
            Self::UpdateAt => ColumnType::DateTime.def(),
            Self::DepartmentId => ColumnType::Uuid.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Department => Entity::belongs_to(super::department::Entity)
                .from(Column::DepartmentId)
                .to(super::department::Column::DepartmentId)
                .into(),
            Self::UserMajor => Entity::has_many(super::user_major::Entity).into(),
        }
    }
}

impl Related<super::department::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Department.def()
    }
}

impl Related<super::user_major::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMajor.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_major::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_major::Relation::Major.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
