//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::RoleEnum;
use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "user"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub user_id: Uuid,
    pub first_name: String,
    pub last_name: String,
    pub address: String,
    pub email: String,
    pub password: String,
    pub is_priority: bool,
    pub cccd: String,
    pub phone_number: String,
    pub is_first_login: bool,
    pub create_at: DateTime,
    pub update_at: DateTime,
    pub deleted_at: Option<DateTime>,
    pub role: RoleEnum,
    pub student_code: Option<String>,
    pub status: UserStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UserId,
    FirstName,
    LastName,
    Address,
    Email,
    Password,
    IsPriority,
    Cccd,
    PhoneNumber,
    IsFirstLogin,
    CreateAt,
    UpdateAt,
    DeletedAt,
    Role,
    StudentCode,
    Status,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UserId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Certificate,
    DocumentType,
    FileUploadHistory,
    OtpVerify,
    Request,
    ScoreBoard,
    SemesterSummary,
    UserMajor,
    UserMfa,
    Wallet,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UserId => ColumnType::Uuid.def(),
            Self::FirstName => ColumnType::String(StringLen::None).def(),
            Self::LastName => ColumnType::String(StringLen::None).def(),
            Self::Address => ColumnType::String(StringLen::None).def(),
            Self::Email => ColumnType::String(StringLen::None).def().unique(),
            Self::Password => ColumnType::String(StringLen::None).def(),
            Self::IsPriority => ColumnType::Boolean.def(),
            Self::Cccd => ColumnType::String(StringLen::None).def(),
            Self::PhoneNumber => ColumnType::String(StringLen::None).def(),
            Self::IsFirstLogin => ColumnType::Boolean.def(),
            Self::CreateAt => ColumnType::DateTime.def(),
            Self::UpdateAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
            Self::Role => RoleEnum::db_type().get_column_type().to_owned().def(),
            Self::StudentCode => ColumnType::String(StringLen::None).def().null(),
            Self::Status => UserStatus::db_type().get_column_type().to_owned().def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Certificate => Entity::has_many(super::certificate::Entity).into(),
            Self::DocumentType => Entity::has_many(super::document_type::Entity).into(),
            Self::FileUploadHistory => Entity::has_many(super::file_upload_history::Entity).into(),
            Self::OtpVerify => Entity::has_many(super::otp_verify::Entity).into(),
            Self::Request => Entity::has_many(super::request::Entity).into(),
            Self::ScoreBoard => Entity::has_many(super::score_board::Entity).into(),
            Self::SemesterSummary => Entity::has_many(super::semester_summary::Entity).into(),
            Self::UserMajor => Entity::has_many(super::user_major::Entity).into(),
            Self::UserMfa => Entity::has_one(super::user_mfa::Entity).into(),
            Self::Wallet => Entity::has_one(super::wallet::Entity).into(),
        }
    }
}

impl Related<super::certificate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Certificate.def()
    }
}

impl Related<super::document_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentType.def()
    }
}

impl Related<super::file_upload_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileUploadHistory.def()
    }
}

impl Related<super::otp_verify::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OtpVerify.def()
    }
}

impl Related<super::request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Request.def()
    }
}

impl Related<super::score_board::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScoreBoard.def()
    }
}

impl Related<super::semester_summary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SemesterSummary.def()
    }
}

impl Related<super::user_major::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMajor.def()
    }
}

impl Related<super::user_mfa::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMfa.def()
    }
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl Related<super::major::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_major::Relation::Major.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_major::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
