//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "votes"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub event_id: i64,
    pub voting_event_id: Uuid,
    pub user_address: String,
    pub user_id: Option<Uuid>,
    pub option: String,
    pub tx_hash: Option<String>,
    pub block_number: Option<i64>,
    pub voted_at: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EventId,
    VotingEventId,
    UserAddress,
    UserId,
    Option,
    TxHash,
    BlockNumber,
    VotedAt,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    VotingEvents,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::EventId => ColumnType::BigInteger.def(),
            Self::VotingEventId => ColumnType::Uuid.def(),
            Self::UserAddress => ColumnType::String(StringLen::None).def(),
            Self::UserId => ColumnType::Uuid.def().null(),
            Self::Option => ColumnType::String(StringLen::None).def(),
            Self::TxHash => ColumnType::String(StringLen::None).def().null(),
            Self::BlockNumber => ColumnType::BigInteger.def().null(),
            Self::VotedAt => ColumnType::DateTime.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::VotingEvents => Entity::belongs_to(super::voting_events::Entity)
                .from(Column::VotingEventId)
                .to(super::voting_events::Column::Id)
                .into(),
        }
    }
}

impl Related<super::voting_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VotingEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
