//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "voting_events"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub event_id: i64,
    pub event_name: String,
    pub description: String,
    pub created_at: DateTime,
    pub end_time: DateTime,
    pub created_by_address: String,
    pub created_by_user_id: Option<Uuid>,
    pub options: Vec<String>,
    pub is_active: bool,
    pub total_votes: i32,
    pub tx_hash: Option<String>,
    pub synced_at: Option<DateTime>,
    pub created_at_db: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EventId,
    EventName,
    Description,
    CreatedAt,
    EndTime,
    CreatedByAddress,
    CreatedByUserId,
    Options,
    IsActive,
    TotalVotes,
    TxHash,
    SyncedAt,
    CreatedAtDb,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Votes,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::EventId => ColumnType::BigInteger.def().unique(),
            Self::EventName => ColumnType::String(StringLen::None).def(),
            Self::Description => ColumnType::Text.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::EndTime => ColumnType::DateTime.def(),
            Self::CreatedByAddress => ColumnType::String(StringLen::None).def(),
            Self::CreatedByUserId => ColumnType::Uuid.def().null(),
            Self::Options => ColumnType::Array(RcOrArc::new(ColumnType::Text)).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::TotalVotes => ColumnType::Integer.def(),
            Self::TxHash => ColumnType::String(StringLen::None).def().null(),
            Self::SyncedAt => ColumnType::DateTime.def().null(),
            Self::CreatedAtDb => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Votes => Entity::has_many(super::votes::Entity).into(),
        }
    }
}

impl Related<super::votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Votes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
